/* Autogenerated by imgtool.py, do not edit. */
const unsigned char ecdsa_pub_key[] = {
    0x30, 0x59, 0x30, 0x13, 0x06, 0x07, 0x2a, 0x86,
    0x48, 0xce, 0x3d, 0x02, 0x01, 0x06, 0x08, 0x2a,
    0x86, 0x48, 0xce, 0x3d, 0x03, 0x01, 0x07, 0x03,
    0x42, 0x00, 0x04, 0xd7, 0x88, 0x74, 0x57, 0x0c,
    0x34, 0x43, 0x9e, 0x32, 0xf3, 0xcb, 0xe2, 0xf9,
    0x68, 0xd5, 0x8e, 0x3e, 0xcb, 0x5a, 0x78, 0x2d,
    0x52, 0x8c, 0x43, 0xa1, 0xff, 0xd5, 0x73, 0xdd,
    0xe9, 0xec, 0x6b, 0x68, 0xad, 0xa7, 0xa5, 0x2c,
    0xa2, 0x48, 0x88, 0xd9, 0xf7, 0xc5, 0x96, 0xfe,
    0x54, 0x07, 0x2e, 0x5f, 0xe4, 0xbf, 0xe6, 0xf7,
    0x8d, 0x77, 0x49, 0xfe, 0x20, 0x01, 0xc1, 0x39,
    0x45, 0x7f, 0x6c,
};
const unsigned int ecdsa_pub_key_len = 91;
const unsigned char ecdsa_priv_key[] = { 0x30, 0x81, 0x87, 0x02, 0x01, 0x00, 0x30, 0x13, 0x06, 0x07, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x02, 0x01, 0x06, 0x08, 0x2a, 0x86, 0x48, 0xce, 0x3d, 0x03, 0x01, 0x07, 0x04, 0x6d, 0x30, 0x6b, 0x02, 0x01, 0x01, 0x04, 0x20, 0xe4, 0x0b, 0xb3, 0xa4, 0x0c, 0xb1, 0xb9, 0x00, 0xef, 0xd3, 0xc5, 0x95, 0x69, 0x72, 0x01, 0x0e, 0x48, 0xca, 0x16, 0x59, 0x69, 0x88, 0xac, 0x1a, 0xee, 0x31, 0x28, 0x28, 0x1b, 0x0f, 0x1a, 0x0b, 0xa1, 0x44, 0x03, 0x42, 0x00, 0x04, 0xa5, 0x76, 0x97, 0xa4, 0xb4, 0x96, 0x0a, 0x08, 0x6c, 0xd7, 0xae, 0x61, 0xd3, 0xd9, 0x35, 0xf9, 0xec, 0x69, 0xf6, 0x09, 0x5f, 0x15, 0x4e, 0x8a, 0x9b, 0x7d, 0x56, 0x51, 0x36, 0xdd, 0xa1, 0xb0, 0x7b, 0xa2, 0xc0, 0x6f, 0x42, 0x4e, 0xcf, 0x34, 0x10, 0x51, 0xc9, 0x15, 0xe4, 0x85, 0x26, 0x63, 0x47, 0xe7, 0x4a, 0xf6, 0x04, 0xa3, 0x0d, 0xf6, 0xf2, 0xe5, 0x6b, 0x5a, 0xf0, 0x50, 0x3d, 0xa0 };
const unsigned int ecdsa_priv_key_len = 138;

#include "FlashIAP.h"
#include "QSPIFBlockDevice.h"
#include "MBRBlockDevice.h"
#include "LittleFileSystem.h"
#include "FATFileSystem.h"

#ifndef CORE_CM7
  #error Update the bootloader by uploading the sketch to the M7 core instead of the M4 core.
#endif

#define BOOTLOADER_ADDR   (0x8000000)
#define SIGNING_KEY_ADDR  (0x8000300)
#define ENCRYPT_KEY_ADDR  (0x8000400)
#define ENCRYPT_KEY_SIZE  (0x0000100)
#define SIGNING_KEY_SIZE  (0x0000100)

mbed::FlashIAP flash;
QSPIFBlockDevice root(QSPI_SO0, QSPI_SO1, QSPI_SO2, QSPI_SO3,  QSPI_SCK, QSPI_CS, QSPIF_POLARITY_MODE_1, 40000000);

bool writeKeys = false;
uint32_t bootloader_data_offset = 0x1F000;
uint8_t* bootloader_data = (uint8_t*)(BOOTLOADER_ADDR + bootloader_data_offset);

uint32_t bootloader_identification_offset = 0x2F0;
uint8_t* bootloader_identification = (uint8_t*)(BOOTLOADER_ADDR + bootloader_identification_offset);

void printProgress(uint32_t offset, uint32_t size, uint32_t threshold, bool reset) {
  static int percent_done = 0;
  if (reset == true) {
    percent_done = 0;
    Serial.println("Flashed " + String(percent_done) + "%");
  } else {
    uint32_t percent_done_new = offset * 100 / size;
    if (percent_done_new >= percent_done + threshold) {
      percent_done = percent_done_new;
      Serial.println("Flashed " + String(percent_done) + "%");
    }
  }
}

void setupMCUBootOTAData() {
  mbed::MBRBlockDevice ota_data(&root, 2);
  mbed::FATFileSystem ota_data_fs("fs");
  
  int err = ota_data_fs.reformat(&ota_data);
  if (err) {
    Serial.println("Error creating MCUboot FAT partition! Please partition QSPI manually first.");
  } else {
    Serial.println("FAT Partition MBR2 reformatted successfully.");
  }

  // Pre-allocate scratch and update bin files with 0xFF bytes to save flash wear on OTA downloads
  FILE* fp = fopen("/fs/scratch.bin", "wb");
  const int scratch_file_size = 128 * 1024;
  uint8_t buffer[128];
  memset(buffer, 0xFF, sizeof(buffer));
  int size = 0;

  Serial.println("\nAllocating scratch file");
  printProgress(size, scratch_file_size, 10, true);
  while (size < scratch_file_size) {
    int ret = fwrite(buffer, sizeof(buffer), 1, fp);
    if (ret != 1) {
      Serial.println("Error writing scratch file");
      break;
    }
    size += sizeof(buffer);
    printProgress(size, scratch_file_size, 10, false);
  }
  fclose(fp);

  fp = fopen("/fs/update.bin", "wb");
  const int update_file_size = 15 * 128 * 1024; // 1.92 MB
  size = 0;

  Serial.println("\nAllocating update file (1.92 MB)");
  printProgress(size, update_file_size, 10, true);
  while (size < update_file_size) {
    int ret = fwrite(buffer, sizeof(buffer), 1, fp);
    if (ret != 1) {
      Serial.println("Error writing update file");
      break;
    }
    size += sizeof(buffer);
    printProgress(size, update_file_size, 5, false);
  }

  fclose(fp);
  Serial.println("\nMCUboot QSPI Data ready.");
}

void applyUpdate() {
  flash.init();
  setupMCUBootOTAData();
  flash.program(&ecdsa_priv_key, ENCRYPT_KEY_ADDR, ENCRYPT_KEY_SIZE);
  flash.program(&ecdsa_pub_key, SIGNING_KEY_ADDR, SIGNING_KEY_SIZE);
  flash.deinit();
  Serial.println("\nSenax Security Keys provisioned successfully.");
}

bool waitResponse() {
  bool confirmation = false;
  while (confirmation == false) {
    if (Serial.available()) {
      char choice = Serial.read();
      switch (choice) {
        case 'y':
        case 'Y':
          return true;
        case 'n':
        case 'N':
          return false;
      }
    }
  }
  return false;
}

void setup() {
  Serial.begin(115200);
  while (!Serial) {}

  uint8_t currentBootloaderVersion = bootloader_data[1];
  String currentBootloaderIdentifier = String(bootloader_identification, 15);

  if((currentBootloaderVersion > 24) && (currentBootloaderIdentifier.equals("MCUboot Arduino"))) {
    Serial.println("=========================================");
    Serial.println("SENAX PROVISIONING TOOL: MCUBoot USB INIT");
    Serial.println("=========================================");
    Serial.println("This sketch will burn the Senax Public Signing and Private Encrypt keys.");
    Serial.println("WARNING: Future sketches MUST be uploaded with Security Settings -> Signing + Encryption using Zephyr imgtool.");
    Serial.println("WARNING: This will DESTROY all current configuration on the QSPI disk.");
    Serial.println("Do you want to proceed and load the custom Senax keys? Y/[n]");
    
    if (waitResponse()) {
      Serial.println("\nKeys will be loaded, and QSPI will be formatted to FAT/MBR2 for OTA updates...");
      writeKeys = true;
    } else {
      Serial.println("\nAborted.");
    }
  } else {
    Serial.println("FATAL ERROR: Security features are not available for this bootloader version.");
    Serial.println("Please update it using STM32H747_manageBootloader sketch first.");
    while(true){ delay(1000); }
  }
  
  if (writeKeys) {
    applyUpdate();
    Serial.println("System provisioned. It's now safe to reboot or disconnect your board.");
  }
}

void loop() {
  delay(1000);
}
